In [7]:
import pandas as pd
import numpy as np
import sympy as sy
from numpy.random import randn

In [8]:
array_1 = np.array([1,2,3])

In [9]:
print(array_1)

[1 2 3]


In [10]:
type(array_1)

numpy.ndarray

In [11]:
array_2 = np.array([-1,4,2])

In [12]:
print(array_2)

[-1  4  2]


In [14]:
len(array_2)

3

In [17]:
# We want to perform the dot product of these two numpy 
#arrray
for i in range(len(array_1)):
    dot = sum(array_1*array_2)
print(dot)

13


In [18]:
array_1@array_2

13

In [19]:
array_1.dot(array_2)

13

In [24]:
array_3 = array_1*2
array_3

array([2, 4, 6])

In [26]:
L1 = [1,2,3]
L2  = L1*2
L2

[1, 2, 3, 1, 2, 3]

In [28]:
array_4 = np.sqrt(array_1)
print(array_4)

[1.         1.41421356 1.73205081]


In [29]:
array_5 = array_4 +array_1
print(array_5)

[2.         3.41421356 4.73205081]


In [30]:
# Broadcasting

In [40]:
array_6 = np.array([1,2,3,4,5,6,7,8,9])

In [42]:
array_6[0:2] = 100
print(array_6)

[100 100   3   4   5   6   7   8   9]


In [44]:
array_6[3:7] = 1

In [45]:
print(array_6)

[100 100   3   1   1   1   1   8   9]


In [46]:
# Matrices

In [52]:
M = np.array([[1,2,3],[4,5,6],[7,8,9]])
M

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [53]:
L = np.linspace(1,9,9)
L

array([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [ ]:
M = L.reshape(3,3)