In [7]:
import pandas as pd
import numpy as np
import sympy as sy
from numpy.random import randn

In [8]:
array_1 = np.array([1,2,3])

In [9]:
print(array_1)

[1 2 3]


In [10]:
type(array_1)

numpy.ndarray

In [11]:
array_2 = np.array([-1,4,2])

In [12]:
print(array_2)

[-1  4  2]


In [14]:
len(array_2)

3

In [17]:
# We want to perform the dot product of these two numpy 
#arrray
for i in range(len(array_1)):
    dot = sum(array_1*array_2)
print(dot)

13


In [18]:
array_1@array_2

13

In [19]:
array_1.dot(array_2)

13

In [24]:
array_3 = array_1*2
array_3

array([2, 4, 6])

In [26]:
L1 = [1,2,3]
L2  = L1*2
L2

[1, 2, 3, 1, 2, 3]

In [28]:
array_4 = np.sqrt(array_1)
print(array_4)

[1.         1.41421356 1.73205081]


In [29]:
array_5 = array_4 +array_1
print(array_5)

[2.         3.41421356 4.73205081]


In [30]:
# Broadcasting

In [40]:
array_6 = np.array([1,2,3,4,5,6,7,8,9])

In [42]:
array_6[0:2] = 100
print(array_6)

[100 100   3   4   5   6   7   8   9]


In [44]:
array_6[3:7] = 1

In [45]:
print(array_6)

[100 100   3   1   1   1   1   8   9]


In [46]:
# Matrices

In [52]:
M = np.array([[1,2,3],[4,5,6],[7,8,9]])
M

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [53]:
L = np.linspace(1,9,9)
L

array([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [55]:
M = L.reshape(3,3)

In [56]:
M

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [59]:
M3 = np.random.randn(1,7,4)
M3

array([[[-0.66537613, -0.77616062, -1.5352172 , -1.03828507],
        [ 0.36733342,  1.20942598,  0.64209822, -0.87828917],
        [-0.02264135, -1.69677581,  0.57066231, -0.57063992],
        [ 0.68563991,  1.03155554, -0.8923303 , -0.61672011],
        [-0.22703843, -0.35264317,  0.41914846, -0.31763992],
        [-0.78924015, -0.36468946, -0.75824076,  2.77437757],
        [-1.59360844, -0.73448738, -0.05069456,  1.38716908]]])

In [61]:
N = np.random.randn(1,4)
N

array([[-1.6203435 ,  1.10337801,  0.25276804,  1.55062383]])

In [64]:
# Identity matrix
I = np.eye(3,4)
I

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [68]:
# Zero Matrix
Z = np.zeros([3,5])
Z

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [74]:
M

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [70]:
D = np.diag(M)

In [71]:
D

array([1., 5., 9.])

In [73]:
E = np.diag(D)
E

array([[1., 0., 0.],
       [0., 5., 0.],
       [0., 0., 9.]])

In [78]:
O = np.ones([3,4])
O

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [97]:
np.linalg.det(M)

-9.51619735392994e-16

In [93]:
M1 = sy.Matrix([[1,2,3],[7,0,6],[7,1,9]])
M1

Matrix([
[1, 2, 3],
[7, 0, 6],
[7, 1, 9]])

In [110]:
V = M1.inv()
V

Matrix([
[  2/9,    5/9,  -4/9],
[  7/9,    4/9,  -5/9],
[-7/27, -13/27, 14/27]])

In [111]:
np.matmul(V,M1)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]], dtype=object)

In [112]:
M1.det()

-27

In [113]:
V

Matrix([
[  2/9,    5/9,  -4/9],
[  7/9,    4/9,  -5/9],
[-7/27, -13/27, 14/27]])

In [114]:
 V.row_del(0)

In [115]:
V

Matrix([
[  7/9,    4/9,  -5/9],
[-7/27, -13/27, 14/27]])

In [131]:
P = sy.Matrix(np.random.randint(1,10,size=(4,4)))
P

Matrix([
[3, 8, 1, 8],
[4, 9, 5, 6],
[3, 2, 2, 3],
[4, 1, 3, 5]])

In [132]:
Q = sy.Matrix(np.random.randint(1,10,size=(4,3)))
Q

Matrix([
[2, 2, 1],
[6, 2, 8],
[7, 7, 2],
[5, 7, 3]])

In [133]:
R = np.matmul(P,Q)
# A*B The number of colums of the left matrix must
# be equal to the number of rows of the right
# matrix

In [134]:
sy.Matrix(R)

Matrix([
[101,  85,  93],
[127, 103, 104],
[ 47,  45,  32],
[ 60,  66,  33]])

In [138]:
# S is 4x1
S  = sy.Matrix(np.random.randint(1,10,4))
S

Matrix([
[8],
[5],
[5],
[2]])

In [139]:
# P is 4x4
P

Matrix([
[3, 8, 1, 8],
[4, 9, 5, 6],
[3, 2, 2, 3],
[4, 1, 3, 5]])

In [140]:
# S*P is impossible

In [141]:
# P*S  is possible
P*S

Matrix([
[ 85],
[114],
[ 50],
[ 62]])